---
kind: pipeline
name: node10-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: test
  image: arm64v8/node:10
  commands:
  - apt-get update
  - apt-get install -y opam zip
  - opam init
  - eval $(opam config env)
  - opam switch install 4.05.0
  - eval $(opam config env)
  - opam pin add flowtype . -n
  - opam depext -u flowtype
  - opam install flowtype --deps-only
  - opam install js_of_ocaml 
  - eval $(opam config env)
  - make all
  - ./bin/flow --help
  - zip ./bin/flow-linux-arm64.zip ./bin/flow
  
- name: build-tag
  image: plugins/github-release
  commands:
  - "go build -v -ldflags \"-X main.version=${DRONE_TAG##v}\" -a -tags netgo -o release/linux/amd64/drone-github-release"
  when:
    event:
    - tag
  
- name: publish
  image: plugins/github-release
  settings:
    api_key: 983273049cf924e758e0c251bfdbc7aa6080ba9f
    event: tag
    files:
      - ./bin/flow-linux-arm64.zip
  
  when:
    event: tag
