---
kind: pipeline
name: node10-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: test
  image: arm64v8/node:10
  commands:
  - npm install --unsafe-perm
  - npm test

# ---
# kind: pipeline
# name: node8-arm64

# platform:
#   os: linux
#   arch: arm64

# steps:
# - name: test
#   image: node:8
#   commands:
#   - npm install
#   - npm test
